import { test, expect } from '@playwright/test'

test('Additional source records can be filtered, paged and retrieved with distinct amendments', async ({ page }) => {
  await page.goto('/#/bills')
  await page.getByLabel('Biennium', { exact: true }).selectOption('2025-26')
  await expect(page.getByText('150 bills', { exact: true })).toBeVisible()
  await expect(page.locator('main table tbody tr')).toHaveCount(25)
  await page.getByRole('navigation', { name: 'Bills pagination' }).getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByText('26 to 50 of 150', { exact: true })).toBeVisible()
  await page.locator('#bq').fill('1960')
  await page.locator('main').getByRole('link', { name: 'E3SHB 1960', exact: true }).click()
  await page.getByRole('tab', { name: 'Versions & Amendments', exact: true }).click()
  await expect(page.getByRole('cell', { name: '1960-S3 AMH CONN H3612.1', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: '1960-S3 AMH ORCU H3611.1', exact: true })).toBeVisible()
})

async function role(page: any, name: string, person?: string) {
  await page.locator('button[aria-haspopup="true"]').first().click()
  await page.locator('#role-sel').selectOption(name)
  if (person) await page.locator('#person-sel').selectOption({ label: person })
  await page.locator('button[aria-haspopup="true"]').first().click()
}

test('Official bill complete assignment / publication journey', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/#/bills/LSC-2025-26-1960')
  await expect(page.getByText('Washington Legislature source feed', { exact: true })).toBeVisible()
  await role(page, 'Assigner')
  await page.getByRole('button', { name: 'Start Tracking', exact: true }).click()
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  const analyst = await page.locator('#preparerId option:checked').textContent(), reviewer = await page.locator('#reviewerId option:checked').textContent()
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await page.getByRole('button', { name: 'Create assignments', exact: true }).click()
  await page.getByRole('tab', { name: 'Analyses', exact: true }).click()
  const link = page.locator('main a[href*="#/analyses/BA-2026-"]').first()
  const href = await link.getAttribute('href'); await link.click()
  await role(page, 'Analyst', analyst!)
  const editor = page.getByRole('textbox', { name: 'Analysis text', exact: true })
  await editor.fill('The grant program requires administrative guidance from DOR.')
  await page.getByLabel('Has issues', { exact: true }).check()
  await page.getByLabel('Issue notes (internal)').fill('Clarify administrative cost assumptions.')
  await page.getByRole('button', { name: 'Mark done and notify next', exact: true }).click()
  await role(page, 'Reviewer', reviewer!)
  await page.getByRole('link', { name: 'Review and deliver', exact: true }).click()
  await page.getByRole('button', { name: 'Approve', exact: true }).click()
  await role(page, 'Manager')
  await page.goto('/' + href)
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  await expect(page.getByText('Published revision 1', { exact: false })).toBeVisible()
  await editor.fill('Updated analysis after clarification from the grant administrator.')
  await expect(page.getByText('Published — Changes Pending', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: /Re-publish/ })).toBeDisabled()
  await role(page, 'Analyst', analyst!)
  await page.getByRole('button', { name: 'Mark done and notify next', exact: true }).click()
  await role(page, 'Reviewer', reviewer!)
  await page.getByRole('link', { name: 'Review and deliver', exact: true }).click()
  await page.getByRole('button', { name: 'Approve', exact: true }).click()
  await role(page, 'Manager')
  await page.goto('/' + href)
  await page.getByRole('button', { name: /Re-publish/ }).click()
  await expect(page.getByText('Published revision 2', { exact: false })).toBeVisible()
  await expect(page.getByText('Published revision 1', { exact: false })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Analysis not found', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('Only 72-hour simulated hearings raise alerts and persona assignments are available', async ({ page }) => {
  await page.goto('/#/hearings')
  await expect(page.locator('main table tbody tr')).toHaveCount(4)
  await expect(page.locator('main table')).toContainText('(simulated)')
  await page.goto('/#/notifications')
  await expect(page.getByText(/Hearing within 72 hours:/)).toHaveCount(3)
  await page.goto('/#/analyses')
  await expect(page.locator('main a[href*="#/analyses/BA-"]').first()).toBeVisible()
})

test('Mobile hearing source history remains usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/hearings')
  await page.getByLabel('Hearing period').selectOption('All')
  await expect(page.locator('main table tbody tr').first()).toBeVisible()
  await page.locator('main table tbody tr').first().getByRole('link').click()
  await expect(page.getByText('Legislative hearings', { exact: true })).toBeVisible()
})

test('Official dataset supports all operational views without synthetic session assumptions', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/#/bills'); await role(page, 'Manager')
  for (const path of ['/', '/analyses', '/estimates', '/packages', '/fiscal', '/implementation', '/reports?tab=query', '/compare']) {
    await page.goto('/#' + path)
    await expect(page.locator('main h1').first()).toBeVisible()
    await expect(page.locator('main')).not.toContainText('2027 regular session')
    await expect(page.locator('body')).not.toContainText(/\bdemo\b/i)
  }
  await role(page, 'Administrator')
  for (const path of ['/admin/templates', '/admin/ids']) {
    await page.goto('/#' + path)
    await expect(page.locator('main h1').first()).toBeVisible()
  }
  expect(errors).toEqual([])
})

test('Browser scrolls the page while the compact sidebar stays in place', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 768 })
  await page.goto('/#/bills'); await role(page, 'Administrator')
  await expect(page.locator('main table tbody tr').first()).toBeVisible()
  const nav = page.getByRole('navigation', { name: 'Main', exact: true })
  const content = page.locator('[data-page-content]')
  expect(await content.evaluate(el => getComputedStyle(el).overflowY)).toBe('visible')
  const menu = nav.locator('ul')
  const collapse = nav.getByRole('button', { name: 'Collapse navigation' })
  expect(await menu.evaluate(el => el.scrollHeight <= el.clientHeight)).toBe(true)
  await expect(nav.getByRole('link', { name: 'Admin', exact: true })).toBeInViewport()
  expect(await menu.evaluate(el => getComputedStyle(el).scrollbarWidth)).toBe('none')
  await page.setViewportSize({ width: 1280, height: 600 })
  const initialNavTop = await nav.evaluate(el => el.getBoundingClientRect().top)
  const initialMainTop = await page.locator('main').evaluate(el => el.getBoundingClientRect().top)
  const initialCollapseTop = await collapse.evaluate(el => el.getBoundingClientRect().top)
  await page.evaluate(() => window.scrollTo(0, 400))
  const offset = await page.evaluate(() => window.scrollY)
  expect(offset).toBeGreaterThan(0)
  expect(await content.evaluate(el => el.scrollTop)).toBe(0)
  expect(await nav.evaluate(el => el.getBoundingClientRect().top)).toBeCloseTo(initialNavTop)
  expect(await page.locator('main').evaluate(el => el.getBoundingClientRect().top)).toBeCloseTo(initialMainTop - offset)
  expect(await menu.evaluate(el => el.scrollTop)).toBe(0)
  await menu.evaluate(el => el.scrollTo(0, el.scrollHeight))
  expect(await menu.evaluate(el => el.scrollTop)).toBeGreaterThan(0)
  await expect(nav.getByRole('link', { name: 'Admin', exact: true })).toBeInViewport()
  await expect(collapse).toBeInViewport()
  expect(await collapse.evaluate(el => el.getBoundingClientRect().top)).toBeCloseTo(initialCollapseTop)
  expect(await page.evaluate(() => window.scrollY)).toBe(offset)
  await collapse.click()
  await expect(nav.getByRole('button', { name: 'Expand navigation' })).toBeInViewport()
  await nav.getByRole('link', { name: 'Admin', exact: true }).click()
  await expect(page.locator('main h1').first()).toBeInViewport()
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
})

test('Implementation bills show official legislative details without invented tasks', async ({ page }) => {
  await page.goto('/#/bills'); await role(page, 'Manager')
  await page.goto('/#/implementation')
  const details = page.getByRole('region', { name: 'Legislative details for E3SHB 1960', exact: true })
  await expect(details).toContainText('Encouraging renewable energy in Washington')
  await expect(details).toContainText('C 260 L 26')
  await expect(details).toContainText('Effective date 1/1/2028.')
  await expect(details).toContainText('Ramel')
  await expect(details.getByRole('link', { name: 'View full bill details' })).toHaveAttribute('href', '#/bills/LSC-2025-26-1960')
  await page.locator('#tb').selectOption('LSC-2025-26-1960')
  await page.locator('#tt').fill('Assess implementation requirements')
  await page.getByRole('button', { name: 'Assign task', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Assess implementation requirements', exact: true })).toBeVisible()
})

test('My Work contains assignments for every login role', async ({ page }) => {
  await page.goto('/#/queue')
  for (const name of ['Analyst', 'Reviewer', 'Assigner', 'Manager', 'Executive Reviewer', 'Leadership', 'Expenditure Contributor', 'Budget Office', 'Read-only', 'Administrator']) {
    await role(page, name)
    await expect(page.locator('main table tbody tr').first()).toBeVisible()
  }
  await role(page, 'Reviewer')
  await page.getByRole('tab', { name: /Needs My Review/ }).click()
  await expect(page.locator('main table tbody tr').first()).toBeVisible()
})

test('Populated estimates and data requests open and retain response edits', async ({ page }) => {
  await page.goto('/#/estimates')
  await expect(page.locator('main table tbody tr')).toHaveCount(8)
  await page.locator('main table tbody tr').first().getByRole('link').click()
  await expect(page.getByLabel('Summary of the fiscal impact', { exact: true })).toHaveValue(/Mock planning estimate/)
  await page.goto('/#/estimates?tab=DR')
  await expect(page.locator('main table tbody tr')).toHaveCount(8)
  const link = page.locator('main table tbody tr').first().getByRole('link')
  const href = await link.getAttribute('href')
  await link.click()
  await expect(page.locator('main dd').filter({ hasText: 'House committee staff' })).toBeVisible()
  await page.getByLabel('Response text', { exact: true }).fill('Reviewed the available program data with the agency team.')
  await page.locator('main').getByRole('link', { name: 'Estimates & Data Requests', exact: true }).click()
  await page.goto('/' + href)
  await expect(page.getByLabel('Response text', { exact: true })).toHaveValue('Reviewed the available program data with the agency team.')
})

test('Fiscal-note status chart contains records in all seven categories', async ({ page }) => {
  await page.goto('/#/queue'); await role(page, 'Manager'); await page.goto('/#/')
  await expect(page.getByRole('img', { name: /^Fiscal notes by status/ })).toHaveAttribute('aria-label', 'Fiscal notes by status. Assigned: 7; In progress: 5; In review: 4; Rework: 2; Executive review: 3; Approved: 6; Delivered: 3')
})
