import { useState } from 'react'
import { useMe, useStore } from '../store'
import { searchWorkspace } from '../search'
import { A, Card, DataTable, Field, PageHeader, Select, inputCls } from '../components/ui'
export default function Search() {
  const { data, role } = useStore(), user = useMe()
  const [q, setQ] = useState(''), [session, setSession] = useState('All'), [kind, setKind] = useState('All'), [status, setStatus] = useState('All'), [owner, setOwner] = useState('All')
  const results = searchWorkspace(data, role, user, q)
  const rows = results.filter(r => (session === 'All' || r.session === session) && (kind === 'All' || r.kind === kind) && (status === 'All' || r.status === status) && (owner === 'All' || r.owner === owner))
  return <><PageHeader title="Search" subtitle="Search legislative source records and authorized work products across historical sessions." /><Card className="mb-4"><div className="grid gap-3 md:grid-cols-3"><Field label="Search terms" htmlFor="search-query"><input id="search-query" className={inputCls} value={q} onChange={e => setQ(e.target.value)} /></Field><Field label="Biennium / session" htmlFor="search-session"><Select id="search-session" value={session} onChange={setSession} options={['All', ...data.sessions.map(s => s.id)]} /></Field><Field label="Result type" htmlFor="search-kind"><Select id="search-kind" value={kind} onChange={setKind} options={['All', ...new Set(results.map(r => r.kind))]} /></Field><Field label="Status" htmlFor="search-status"><Select id="search-status" value={status} onChange={setStatus} options={['All', ...new Set(results.map(r => r.status))]} /></Field><Field label="Owner" htmlFor="search-owner"><Select id="search-owner" value={owner} onChange={setOwner} options={[{ value: 'All', label: 'All owners' }, ...data.staff.map(s => ({ value: s.id, label: s.name }))]} /></Field></div></Card><Card pad={false}><DataTable caption={`${rows.length} search results`} rows={rows} rowKey={r => `${r.kind}-${r.id}`} cols={[{ key: 'kind', header: 'Type', render: r => r.kind }, { key: 'label', header: 'Result', render: r => <A to={r.link}>{r.label}</A> }, { key: 'session', header: 'Session', render: r => r.session }, { key: 'status', header: 'Status', render: r => r.status }]} /></Card></>
}
